{
  "swagger": "2.0",
  "info": {
    "description": "All irislcd supported APIs will be shown by this swagger-ui page. You can access these APIs through this page.",
    "version": "1.0",
    "title": "irislcd Swagger-UI",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "name": "API Support",
      "url": "http://www.swagger.io/support",
      "email": "support@swagger.io"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "basePath": "/",
  "paths": {
    "/node_version": {
      "get": {
        "tags": [
          "Version"
        ],
        "summary": "Get the version of connected full node",
        "description": "Get the version of connected full node",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/common.HTTPError"
            }
          }
        }
      }
    },
    "/version": {
      "get": {
        "tags": [
          "Version"
        ],
        "summary": "Get irislcd version",
        "description": "Get irislcd version",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/common.HTTPError"
            }
          }
        }
      }
    },
    "/bank/accounts/{address}": {
      "get": {
        "tags": [
          "ICS20: Bank"
        ],
        "summary": "Get token information",
        "description": "Get token information of user specific address",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "address",
            "in": "path",
            "description": "address",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/bank.AccountQueryResponse"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/common.HTTPError"
            }
          }
        }
      }
    },
    "/bank/coin/{coin-type}": {
      "get": {
        "tags": [
          "ICS20: Bank"
        ],
        "summary": "Get coin type",
        "description": "Get the detailed information about the given coin type",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "coin-type",
            "in": "path",
            "description": "coin-type name",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/bank.CoinTypeResponse"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/common.HTTPError"
            }
          }
        }
      }
    },
    "/bank/{address}/send": {
      "post": {
        "tags": [
          "ICS20: Bank"
        ],
        "summary": "Transfer tokens",
        "description": "Transfer tokens to given address.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "address",
            "description": "address to send token",
            "required": true,
            "type": "string"
          },
          {
            "in": "query",
            "name": "generate-only",
            "description": "if true, only generate and return a unsigned transaction byte array",
            "required": false,
            "type": "boolean"
          },
          {
            "in": "query",
            "name": "async",
            "description": "if true, broadcast transaction asynchronously",
            "required": false,
            "type": "boolean"
          },
          {
            "in": "body",
            "name": "sendToken",
            "description": "parameters to send token",
            "required": true,
            "schema": {
              "$ref": "#/definitions/bank.TransferBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/common.BroadcastTxCommitResult"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/common.HTTPError"
            }
          }
        }
      }
    },
    "/keys": {
      "get": {
        "description": "Get all keys in the key store",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "ICS1: Key Management"
        ],
        "summary": "list all keys",
        "operationId": "queryKeysRequest",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/keys.KeyOutputsResponse"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          }
        }
      },
      "post": {
        "description": "Create a new key and persistent it to the key store",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "ICS1: Key Management"
        ],
        "summary": "Create a account",
        "parameters": [
          {
            "description": "name and password for a new key",
            "name": "CreateNewKeyBody",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/keys.NewKeyBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/keys.NewKeyBody"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          }
        }
      }
    },
    "/keys/{name}/sign": {
      "post": {
        "description": "Sign user specified byte array, tx byte array must be base64 encoding",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "ICS1: Key Management"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "key name",
            "name": "name",
            "required": true,
            "in": "path"
          },
          {
            "description": "seed and password for a new key",
            "name": "txAndPwd",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/keys.SignBody"
            }
          }
        ],
        "summary": "Sign user specified bytes array",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          }
        }
      }
    },
    "/keys/{name}": {
      "get": {
        "description": "Get key detailed information by its name",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "ICS1: Key Management"
        ],
        "summary": "Get key information",
        "parameters": [
          {
            "type": "string",
            "description": "key name",
            "name": "name",
            "required": true,
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/keys.KeyOutputResponse"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          }
        }
      },
      "put": {
        "description": "Update key password",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "ICS1: Key Management"
        ],
        "summary": "Update key password",
        "parameters": [
          {
            "type": "string",
            "description": "key name",
            "name": "name",
            "required": true,
            "in": "path"
          },
          {
            "description": "key name",
            "name": "pwd",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/keys.UpdateKeyBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          }
        }
      },
      "delete": {
        "description": "Delete key by its name",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "ICS1: Key Management"
        ],
        "summary": "Delete key by its name",
        "parameters": [
          {
            "type": "string",
            "description": "key name",
            "name": "name",
            "required": true,
            "in": "path"
          },
          {
            "description": "password",
            "name": "pwd",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/keys.DeleteKeyBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          }
        }
      }
    },
    "/gov/proposals": {
      "post": {
        "description": "Send transaction to launch a proposal",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "ICS22: Governance"
        ],
        "summary": "Launch a proposal",
        "parameters": [
          {
            "in": "query",
            "name": "generate-only",
            "description": "if true, only generate and return a unsigned transaction byte array",
            "required": false,
            "type": "boolean"
          },
          {
          "in": "query",
          "name": "async",
          "description": "if true, broadcast transaction asynchronously",
          "required": false,
          "type": "boolean"
          },
          {

            "description": "proposal information",
            "name": "postProposalBody",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/gov.PostProposalBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.BroadcastTxCommitResult"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          }
        }
      },
      "get": {
        "description": "Query proposals information with parameters",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "ICS22: Governance"
        ],
        "summary": "Query proposals",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/gov.TextProposalsResponse"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          }
        }
      }
    },
    "/gov/proposals/{proposal-id}/deposits": {
      "post": {
        "description": "Send transaction to deposit token to proposal",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "ICS22: Governance"
        ],
        "summary": "Deposit token to a proposal",
        "parameters": [
          {
            "in": "query",
            "name": "generate-only",
            "description": "if true, only generate and return a unsigned transaction byte array",
            "required": false,
            "type": "boolean"
          },
          {
            "in": "query",
            "name": "async",
            "description": "if true, broadcast transaction asynchronously",
            "required": false,
            "type": "boolean"
          },
          {
            "type": "string",
            "description": "proposal id",
            "name": "proposal-id",
            "required": true,
            "in": "path"
          },
          {
            "description": "deposit information",
            "name": "depositBody",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/gov.DepositBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.BroadcastTxCommitResult"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          }
        }
      }
    },
    "/gov/proposals/{proposal-id}/votes": {
      "post": {
        "description": "Send transaction to vote a proposal",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "ICS22: Governance"
        ],
        "summary": "Vote a proposal",
        "parameters": [
          {
            "in": "query",
            "name": "generate-only",
            "description": "if true, only generate and return a unsigned transaction byte array",
            "required": false,
            "type": "boolean"
          },
          {
            "in": "query",
            "name": "async",
            "description": "if true, broadcast transaction asynchronously",
            "required": false,
            "type": "boolean"
          },
          {
            "type": "string",
            "description": "proposal id",
            "name": "proposal-id",
            "required": true,
            "in": "path"
          },
          {
            "description": "vote information",
            "name": "voteBody",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "$ref": "#/definitions/gov.VoteBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.BroadcastTxCommitResult"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          }
        }
      },
      "get": {
        "description": "Query voters information by proposal-id",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "ICS22: Governance"
        ],
        "summary": "Query voters",
        "parameters": [
          {
            "type": "string",
            "description": "proposal id",
            "name": "proposal-id",
            "required": true,
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/gov.VotesResponse"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          }
        }
      }
    },
    "/gov/proposals/{proposal-id}": {
      "get": {
        "description": "Query proposal by id",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "ICS22: Governance"
        ],
        "summary": "Query proposal",
        "parameters": [
          {
            "type": "string",
            "description": "proposal id",
            "name": "proposal-id",
            "required": true,
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/gov.TextProposalResponse"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          }
        }
      }
    },
    "/gov/proposals/{proposal-id}/deposits/{depositer}": {
      "get": {
        "description": "Query deposit by proposal-id and depositer address",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "ICS22: Governance"
        ],
        "summary": "Query deposit",
        "parameters": [
          {
            "type": "string",
            "description": "proposal id",
            "name": "proposal-id",
            "required": true,
            "in": "path"
          },
          {
            "type": "string",
            "description": "depositer address",
            "name": "depositer",
            "required": true,
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/gov.DepositResponse"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          }
        }
      }
    },
    "/gov/proposals/{proposal-id}/votes/{voter}": {
      "get": {
        "description": "Query vote information by proposal-id and voter address",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "ICS22: Governance"
        ],
        "summary": "Query vote",
        "parameters": [
          {
            "type": "string",
            "description": "proposal id",
            "name": "proposal-id",
            "required": true,
            "in": "path"
          },
          {
            "type": "string",
            "description": "voter address",
            "name": "voter",
            "required": true,
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/gov.VoteResponse"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          }
        }
      }
    },
    "/gov/params": {
      "get": {
        "description": "Query parameters which were added or modified by governance",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "ICS22: Governance"
        ],
        "summary": "Query governance parameters",
        "parameters": [
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.KVPairs"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/common.HTTPError"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "common.HTTPError": {
      "type": "object",
      "properties": {
        "rest api": {
          "type": "string",
          "example": "2.0"
        },
        "code": {
          "type": "integer",
          "example": 500
        },
        "error message": {
          "type": "string"
        }
      }
    },
    "common.Coin": {
      "type": "object",
      "properties": {
        "denom": {
          "type": "string"
        },
        "amount": {
          "type": "string"
        }
      }
    },
    "common.Coins": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/common.Coin"
      }
    },
    "common.KVPair": {
      "type": "object",
      "properties": {
        "key": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      }
    },
    "common.KVPairs": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/common.KVPair"
      }
    },
    "common.CheckTxResult": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "data": {
          "type": "string"
        },
        "gas_used": {
          "type": "integer"
        },
        "gas_wanted": {
          "type": "integer"
        },
        "info": {
          "type": "string"
        },
        "log": {
          "type": "string"
        },
        "tags": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/common.KVPairs"
          }
        }
      },
      "example": {
        "code": 0,
        "data": "data",
        "log": "log",
        "gas_used": 6,
        "gas_wanted": 1,
        "info": "info",
        "tags": [
          "",
          ""
        ]
      }
    },
    "common.DeliverTxResult": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "data": {
          "type": "string"
        },
        "gas_used": {
          "type": "integer"
        },
        "gas_wanted": {
          "type": "integer"
        },
        "info": {
          "type": "string"
        },
        "log": {
          "type": "string"
        },
        "tags": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/common.KVPairs"
          }
        }
      },
      "example": {
        "code": 5,
        "data": "data",
        "log": "log",
        "gas_used": 5,
        "gas_wanted": 2,
        "info": "info",
        "tags": [
          "",
          ""
        ]
      }
    },
    "common.BroadcastTxCommitResult": {
      "type": "object",
      "properties": {
        "check_tx": {
          "$ref": "#/definitions/common.CheckTxResult"
        },
        "deliver_tx": {
          "$ref": "#/definitions/common.DeliverTxResult"
        },
        "hash": {
          "type": "string"
        },
        "height": {
          "type": "integer"
        }
      },
      "example": {
        "check_tx": {
          "code": 0,
          "data": "data",
          "log": "log",
          "gas_used": 6,
          "gas_wanted": 1,
          "info": "info",
          "tags": [
            "",
            ""
          ]
        },
        "deliver_tx": {
          "code": 5,
          "data": "data",
          "log": "log",
          "gas_used": 5,
          "gas_wanted": 2,
          "info": "info",
          "tags": [
            "",
            ""
          ]
        },
        "hash": "hash",
        "height": 7
      }
    },
    "common.coinUnit": {
      "type": "object",
      "properties": {
        "denom": {
          "type": "string"
        },
        "decimal": {
          "type": "integer"
        }
      }
    },
    "common.coinUnits": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/common.coinUnit"
      }
    },
    "common.BaseTx": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "chain_id": {
          "type": "string"
        },
        "account_number": {
          "type": "string"
        },
        "sequence": {
          "type": "string"
        },
        "gas": {
          "type": "string"
        },
        "fee": {
          "type": "string"
        }
      }
    },
    "bank.AccountQueryResponse": {
      "type": "object",
      "properties": {
        "account_number": {
          "type": "integer"
        },
        "address": {
          "type": "string"
        },
        "coins": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "public_key": {
          "type": "string"
        },
        "sequence": {
          "type": "integer"
        }
      }
    },
    "bank.TransferBody": {
      "type": "object",
      "properties": {
        "amount": {
          "$ref": "#/definitions/common.Coins"
        },
        "sender": {
          "type": "string"
        },
        "base_tx": {
          "$ref": "#/definitions/common.BaseTx"
        }
      }
    },
    "bank.CoinTypeResponse": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "desc": {
          "type": "string"
        },
        "min_unit": {
          "$ref": "#/definitions/common.coinUnit"
        },
        "Units": {
          "$ref": "#/definitions/common.coinUnits"
        },
        "origin": {
          "type": "integer"
        }
      }
    },
    "keys.DeleteKeyBody": {
      "type": "object",
      "properties": {
        "password": {
          "type": "string"
        }
      }
    },
    "keys.NewKeyBody": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "seed": {
          "type": "string"
        }
      }
    },
    "keys.SignBody": {
      "type": "object",
      "properties": {
        "password": {
          "type": "string"
        },
        "tx_bytes": {
          "type": "string"
        }
      }
    },
    "keys.UpdateKeyBody": {
      "type": "object",
      "properties": {
        "new_password": {
          "type": "string"
        },
        "old_password": {
          "type": "string"
        }
      }
    },
    "keys.KeyOutputResponse": {
      "type": "object",
      "properties": {
        "address": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "pub_key": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "keys.KeyOutputsResponse": {
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "#/definitions/keys.KeyOutputResponse"
      }
    },
    "gov.PostProposalBody": {
      "type": "object",
      "properties": {
        "base_tx": {
          "$ref": "#/definitions/common.BaseTx"
        },
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "proposal_type": {
          "type": "string"
        },
        "proposer": {
          "type": "string"
        },
        "initial_deposit": {
          "$ref": "#/definitions/common.Coins"
        }
      }
    },
    "gov.DepositBody": {
      "type": "object",
      "properties": {
        "base_tx": {
          "$ref": "#/definitions/common.BaseTx"
        },
        "depositer": {
          "type": "string"
        },
        "amount": {
          "$ref": "#/definitions/common.Coins"
        }
      }
    },
    "gov.VoteBody": {
      "type": "object",
      "properties": {
        "base_tx": {
          "$ref": "#/definitions/common.BaseTx"
        },
        "voter": {
          "type": "string"
        },
        "option": {
          "type": "string"
        }
      }
    },
    "gov.TextProposalResponse": {
      "type": "object",
      "properties": {
        "base_req": {
          "$ref": "#/definitions/common.BaseTx"
        },
        "voter": {
          "type": "string"
        },
        "option": {
          "type": "string"
        }
      }
    },
    "gov.DepositResponse": {
      "type": "object",
      "properties": {
        "amount": {
          "$ref": "#/definitions/common.BaseTx"
        },
        "voter": {
          "type": "string"
        },
        "option": {
          "type": "string"
        }
      }
    },
    "gov.VoteResponse": {
      "type": "object",
      "properties": {
        "voter": {
          "type": "string"
        },
        "proposal_id": {
          "type": "integer"
        },
        "option": {
          "type": "string"
        }
      }
    },
    "gov.VotesResponse": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/gov.VoteResponse"
      }
    },
    "gov.TextProposalsResponse": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/gov.TextProposalResponse"
      }
    }
  }
}